@phoneNumber = 12345678
@password = passord123
@api = https://localhost:7272

### Get token
# @name login
POST {{api}}/users/log-in
Content-Type: application/json

{
    "phoneNumber": "{{phoneNumber}}",
  "password": "{{password}}"
}

### Get user by phone number
# @name getUserByPhoneNumber
GET {{api}}/users/get-user-by-phone-number/{{phoneNumber}}
Authorization: Bearer {{login.response.body.token}}


### Get user
# @name getUser
GET {{api}}/users/get-user/{{getUserByPhoneNumber.response.body.id}}
Content-Type: application/json
Authorization: Bearer {{login.response.body.token}}

### decode token
# @name decodeToken
POST {{api}}/users/decode-token
Content-Type: application/json
Authorization: Bearer {{login.response.body.token}}

{
  "Token": "{{login.response.body.token}}"
}

### update user values
# @name updateUserValues
PUT {{api}}/users/update-user-values
Content-Type: application/json
Authorization: Bearer {{login.response.body.token}}

{
  "FirstName": "Ba",
  "LastName": "Etternavn",
  "PhoneNumber": "{{phoneNumber}}",
  "BirthDate": "1111-11-11",
  "Address": "gg 1",
  "PostalCode": "0999",
  "City": "Oslo",
  "Password": "passord123"
}